### ISSUE TITLE
json数据中有五个日期有两个显示不出来

### ISSUE THREAD

**Issue by zhangmingliang1335** [coffeedeveloper/exportjs#1]
![default](https://user-images.githubusercontent.com/22959220/28514875-35882f1c-708e-11e7-8dd5-94e3ac6bf1d0.PNG)
![json](https://user-images.githubusercontent.com/22959220/28514884-406990f6-708e-11e7-990f-c7fac891186f.PNG)

**Comment by coffeedeveloper** [comment]
你用文本编辑器打开CSV文件看下实际内容是什么，看下有没有输出？估计是因为你excel的表格显示属性导致的。

**Comment by zhangmingliang1335** [comment]
导出的数据在execl表中因数据长度问题显示#####这个标识，请问该怎么改，并能在单元格中居中是最好的
![default](https://user-images.githubusercontent.com/22959220/30463381-030c2cca-99fe-11e7-98a1-95799a8c978b.png)
请问下能有什么好用的格式匹配方法吗？

**Comment by coffeedeveloper** [comment]
怎么说呢，csv只是一个纯文本的逗号分隔数据格式，并不能包含任何的样式方面的内容以及设置。需要要实现你的效果，需要用导出excel的库了。 [SheetJS/js-xlsx](https://github.com/SheetJS/js-xlsx)
